# Generated by Django 6.0 on 2026-02-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='farm_size',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='farm_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='water_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
