# Generated by Django 6.0 on 2026-02-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_userlogin_farm_size_userlogin_farm_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(default='', max_length=100)),
                ('scientific_name', models.CharField(default='', max_length=150)),
                ('taxonomy_family', models.CharField(default='', max_length=100)),
                ('habitat', models.CharField(default='', max_length=100)),
                ('water_type', models.CharField(default='', max_length=50)),
                ('threatened_status', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
