# Generated by Django 6.0 on 2026-02-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0003_fishspecies'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitatCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitat_type', models.CharField(default='', max_length=100)),
                ('temp_min', models.IntegerField()),
                ('temp_max', models.IntegerField()),
                ('salinity', models.CharField(default='', max_length=50)),
                ('oxygen_level', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
