# Generated by Django 6.0 on 2026-02-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0004_habitatcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(default='', max_length=100)),
                ('protein_percent', models.IntegerField()),
                ('food_category', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
