# Generated by Django 6.0 on 2026-02-07 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0005_foodtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishFoodMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suitability_score', models.IntegerField(default=0)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish.fishspecies')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish.foodtype')),
            ],
        ),
    ]
