# Generated by Django 6.0 on 2026-02-07 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0006_fishfoodmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(default='', max_length=100)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='fish.fishspecies')),
            ],
        ),
    ]
