# Generated by Django 6.0 on 2026-02-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0007_fishalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishspecies',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
