# Generated by Django 6.0 on 2026-02-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0008_fishspecies_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='farm_size',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='farm_type',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='water_type',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='role',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
