# Generated by Django 6.0 on 2026-02-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0009_remove_userlogin_farm_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='password',
            field=models.CharField(default='', max_length=25),
        ),
    ]
