# Generated by Django 6.0 on 2026-02-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0010_alter_userlogin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
