# Generated by Django 6.0 on 2026-02-12 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0013_alter_recommendation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_type', models.CharField(default='', max_length=25)),
                ('farm_type', models.CharField(default='', max_length=50)),
                ('farm_size', models.FloatField()),
                ('water_temperature', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish.fishspecies')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish.foodtype')),
            ],
        ),
    ]
