# Generated by Django 6.0 on 2026-02-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0014_trainingsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
