# Generated by Django 6.0 on 2026-02-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0015_recommendation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
