# Generated by Django 6.0 on 2026-02-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0016_recommendation_confidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='role',
        ),
    ]
