# Generated by Django 6.0 on 2026-02-14 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0017_remove_userlogin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='fish.foodtype'),
        ),
    ]
