# Generated by Django 6.0 on 2026-02-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0018_recommendation_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fish_images/'),
        ),
    ]
