# Generated by Django 6.0 on 2026-02-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0019_userlogin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishspecies',
            name='fish_img',
            field=models.ImageField(blank=True, null=True, upload_to='fish_images/'),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
