# Generated by Django 6.0 on 2026-02-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0020_fishspecies_fish_img_alter_userlogin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='food_img',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
