# Generated by Django 6.0 on 2026-02-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0021_foodtype_food_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='last_logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
