# Generated by Django 6.0 on 2026-02-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0022_userlogin_last_login_time_userlogin_last_logout_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish.fishspecies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish.userlogin')),
            ],
        ),
    ]
